### ISSUE TITLE
Definition of Range Entropy.

### ISSUE THREAD

**Issue by andrewczgithub** [omidvarnia/RangeEn#1]
Hi @omidvarnia !

I hope your well.

I just trying to get an understanding of the Range Entropy metric.

Does it mean the lower the Range Entropy metric, the more difficult to make a forecast against the time series, moving forward?

Kind regards,
Andrew

**Comment by omidvarnia** [comment]
Dear @andrewczgithub 

Thank you for your interest in my research.

What Range Entropy and other similar measures such as Sample Entropy and Approximate Entropy try to quantify is ‘the amount of information’ which a time series conveys over time. For example, Gaussian noise is completely unpredictable, so it contains ‘maximum information’ and therefore, has a very high entropy. 

On the other hand, purely predictable time series such as a line or a sinusoidal have ‘low information’, so they generate low entropy values. 

In reality, however, we usually deal with ‘complex’ signals which sit somewhere between the two extremes of pure noise and purely predictable time series. A ‘loose’ example could be a line with an additive noise on top of that. More factual examples include physiological signals or stock market fluctuations. In these situations, it may be an oversimplification if we set simple rules like: ‘the higher entropy value, the more difficult to forecast the change’. 

Also, considering entropy values at a single tolerance parameter r could be quite misleading, as it may be easily affected by the choice of r-value. Therefore, my advice would be to consider the ‘pattern’ of entropy changes over multiple tolerance values (r) rather than a single entropy value.

I have written a simple piece of MATLAB code which simulates a few ‘extreme’ examples of synthetic signals and computes their Range Entropy B (modified Sample Entropy) over a span of r-values. You could also try your own signals through the code and see how their Range Entropy patterns change over r. Hope it helps.  

![RAngeEn_B_examples](https://user-images.githubusercontent.com/20547382/71672684-023afd80-2d77-11ea-92a4-f838e963f0cc.png)

```matlab
clear all
clc
close all

%% Parameters of the Range entropy measure (RangeEn-B --> modified version of SampEn)
emb_dim = 2; % Embedding dimension for Range entropy
r_span  = linspace(.05, 1, 20); % Span of the tolerance parameter r for Range entropy

%% Simulate some simple signals
Fs      = 100; % (Hz) A hypothetical sampling rate
T       = 4*pi;   % (sec) A hypothetical length in time
t_span  = linspace(0,T,T*Fs); % Time span over the interval of [0 T] sec

x1      = 10*t_span; % A pure line over t_span 
x2      = sin(t_span); % A pure sinusoid over t_span
x3      = 10*t_span + 0.1*randn(size(t_span)); % A simple line over t_span with a little bit of Gaussian noise on top of it
x4      = sin(t_span) + 0.1*randn(size(t_span)); % A pure sinusoid over t_span with a little bit of Gaussian noise on top of it
x5      = randn(size(t_span)); % A pure Gaussian noise over t_span

E_x1    = zeros(1,length(r_span)); % Range entropy measures of x1 at all r-values in r_span
E_x2    = zeros(1,length(r_span)); % Range entropy measures of x2 at all r-values in r_span
E_x3    = zeros(1,length(r_span)); % Range entropy measures of x3 at all r-values in r_span
E_x4    = zeros(1,length(r_span)); % Range entropy measures of x4 at all r-values in r_span
E_x5    = zeros(1,length(r_span)); % Range entropy measures of x5 at all r-values in r_span

for n_r = 1 : length(r_span)
    
    E_x1(n_r) = RangeEn_B(x1, emb_dim, r_span(n_r));
    E_x2(n_r) = RangeEn_B(x2, emb_dim, r_span(n_r));
    E_x3(n_r) = RangeEn_B(x3, emb_dim, r_span(n_r));
    E_x4(n_r) = RangeEn_B(x4, emb_dim, r_span(n_r));
    E_x5(n_r) = RangeEn_B(x5, emb_dim, r_span(n_r));
    
end

%% Plot the Range entropy curves
figure, plot(r_span,E_x1,'r','linewidth',4)
hold on, plot(r_span,E_x2,'k','linewidth',4)
hold on, plot(r_span,E_x3,'b','linewidth',4)
hold on, plot(r_span,E_x4,'g','linewidth',4)
hold on, plot(r_span,E_x5,'c','linewidth',4)

legend('Pure line', 'Pure sinusoid','Noisy line', 'Noisy sinusoid', 'Gaussian noise')
```

**Comment by andrewczgithub** [comment]
@omidvarnia Thankyou!!
Very clear.
Considering I am using stock market data and trying to use the algorithm to come up with trading rules, It looks like anything below 0.25 seems to be predictable.
Would this be a reasonable assumption of a predictable signal?

Kind regards,
Andrew

**Comment by omidvarnia** [comment]
Dear @andrewczgithub 

With your assumption, it is likely that you predict the simplest (and most extreme) cases only. I think a more factual scenario would be to consider a background volatility (high entropy) in the stock market with some periods of regularity/predictability from time to time. In other words, a better assumption could be a 'time-varying predictability' which is embedded in a highly volatile fluctuation. In this case, you will need to monitor the transitions of RangeEn values over time from high/low to low/high and their low-value intervals. To this end, a straightforward approach is to extract RangeEn from a sliding window with overlap between successive windows over your time series. However, you need to be careful about the choice of an appropriate window length to be neither too short nor too long. Maybe you can try different window lengths and choose the most relevant one by try and error?

Regards;
Amir
